### ISSUE TITLE
[Discussion] Apakah memungkinkan kita mencari hostingan lokal Indonesia untuk menggunakan sebagai VPN?

### ISSUE THREAD

**Issue by variananora** [neneeen/own-vpn-for-everyone#6]
Apakah memungkinkan kita mencari hostingan lokal Indonesia untuk menggunakan sebagai VPN?

Saya udah searching banyak ke beberapa VPS hosting di Indonesia dan semua yang saya cari ada terms and condition dimana tidak boleh dijadikan sebagai proxy/VPN. Kira-kira apakah author tau atau familiar dengan hostingan di Indonesia?

Kenapa ingin hosting lokal Indonesia? Buat nurunin latency aja sih alasannya.

**Comment by sangtsaka** [comment]
i found this tweet https://twitter.com/secgron/status/1398914423499104259?s=09
it may be useful for you sir

**Comment by neneeen** [comment]
Hm, kantor sih ada pake Cloudmatika dan gua pasang SoftEther disitu bertahun-tahun g kena komplain, tapi usagenya lebih untuk para dev kalo butuh IP static yang di whitelist ke klien, bukan untuk personal. Ublek-ublek ToS nya nggak disebut dilarang bikin sebagai VPN. Bukannya biasanya yang dilarang itu kalau *open* proxy ya, soalnya nanti kena abuse complain.

Cuman, ya kasusnya ini kami kebetulan memang udah punya instance lalu sekalian tambahin SoftEther karena toh resourcenya g kepake full, kalau ngliat harga-harga untuk VPS di Jakarta, benere kalah jauh dibanding sekedar misal beli Windscribe yang lokasi Jakarta kena $2 doang dapat unlimited.

**Comment by variananora** [comment]
Jujur aja agak ngeri sih sama ToS ga jelas gitu soalnya pernah buat VPN pribadi kena suspend gara gara ada traffic lewat openvpn gitu. saya sih mau full 24/7 tak VPN-in aja pc ini atau tak hajar langsung lewat mikrotik biar satu rumah internetnya bener. males bentar matiin bentar nyalain jadi kerjaan yang bakalan ganggu gitu.

> i found this tweet [twitter.com/secgron/status/1398914423499104259?s=09](https://twitter.com/secgron/status/1398914423499104259?s=09) it may be useful for you sir

Great info, thank you!

> Cuman, ya kasusnya ini kami kebetulan memang udah punya instance lalu sekalian tambahin SoftEther karena toh resourcenya g kepake full, kalau ngliat harga-harga untuk VPS di Jakarta, benere kalah jauh dibanding sekedar misal beli Windscribe yang lokasi Jakarta kena $2 doang dapat unlimited.

Iya sih VPS Jakarta harganya cukup mahal dan bandwidthnya kurang gede dan ada limit FUP juga...
